version: 2

jobs:
  build:
    docker:
      - image: "debian:stretch"
    steps:
      - checkout
      - run:
          name: Installing GCC
          command: 'apt-get update && apt-get install -y gcc g++'
      - run:
          name: Compiling
          command: 'find . -name "*.cpp" -exec g++ {} -o {}.exec \;'
      - run:
          name: Executing
          command: 'find . -name "*.exec" -exec sh -c ''echo {} && "{}"'' \;'
      - run:
          name: Preparing artifacts
          command: 'find . -name "*.exec" -exec rsync -R {} artifacts \;'
      - store_artifacts:
          path: artifacts
